-- This migration was generated for HU-045
ALTER TABLE `Order` MODIFY `status` ENUM('PENDING', 'PAID', 'PREPARING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'FAILED', 'RETURNED') NOT NULL DEFAULT 'PENDING';
ALTER TABLE `OrderStatusLog` MODIFY `status` ENUM('PENDING', 'PAID', 'PREPARING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'FAILED', 'RETURNED') NOT NULL;
